### ISSUE TITLE
Workend/envisage seems a bit broken on Qt.

### ISSUE THREAD

**Issue by GaelVaroquaux** [enthought/traitsbackendqt#2]
Starting Mayavi with the qt backend gives me a traceback (that is ignored, so the soft starts). Trying to close it gives me another, that prevents closing):

<pre>
$ ETS_TOOLKIT=qt4 mayavi2                  [23:50]
Exception occurred in traits notification handler for object: <enthought.plugins.python_shell.view.python_shell_view.PythonShellView object at 0xa1e7cbc>, trait: stdout_text, old value: <undefined>, new value: Exception occurred in traits notification handler.
Please check the log file for details.
Traceback (most recent call last):
  File "/home/varoquau/dev/enthought/ets/traits/enthought/traits/trait_notifiers.py", line 512, in rebind_call_1
    self.dispatch( getattr( self.object(), self.name ), new )
  File "/home/varoquau/dev/enthought/ets/traits/enthought/traits/trait_notifiers.py", line 622, in dispatch
    handler( *args )
  File "/home/varoquau/dev/enthought/ets/envisageplugins/enthought/plugins/python_shell/view/python_shell_view.py", line 242, in _on_write_stdout
    self.shell.control.write(text)
  File "/home/varoquau/dev/enthought/ets/traitsbackendqt/enthought/pyface/ui/qt4/python_shell.py", line 156, in write
    if not self._hidden:
AttributeError: 'PyfacePythonWidget' object has no attribute '_hidden'
ERROR|2011-04-17 23:50:35,958|Exception occurred in traits notification handler for object: <enthought.plugins.python_shell.view.python_shell_view.PythonShellView object at 0xa1e7cbc>, trait: stdout_text, old value: <undefined>, new value: Exception occurred in traits notification handler.
Please check the log file for details.
Traceback (most recent call last):
  File "/home/varoquau/dev/enthought/ets/traits/enthought/traits/trait_notifiers.py", line 512, in rebind_call_1
    self.dispatch( getattr( self.object(), self.name ), new )
  File "/home/varoquau/dev/enthought/ets/traits/enthought/traits/trait_notifiers.py", line 622, in dispatch
    handler( *args )
  File "/home/varoquau/dev/enthought/ets/envisageplugins/enthought/plugins/python_shell/view/python_shell_view.py", line 242, in _on_write_stdout
    self.shell.control.write(text)
  File "/home/varoquau/dev/enthought/ets/traitsbackendqt/enthought/pyface/ui/qt4/python_shell.py", line 156, in write
    if not self._hidden:
AttributeError: 'PyfacePythonWidget' object has no attribute '_hidden'
Exception occurred in traits notification handler for object: <enthought.plugins.python_shell.view.python_shell_view.PythonShellView object at 0xa1e7cbc>, trait: stdout_text, old value: <undefined>, new value: 
Traceback (most recent call last):
  File "/home/varoquau/dev/enthought/ets/traits/enthought/traits/trait_notifiers.py", line 512, in rebind_call_1
    self.dispatch( getattr( self.object(), self.name ), new )
  File "/home/varoquau/dev/enthought/ets/traits/enthought/traits/trait_notifiers.py", line 622, in dispatch
    handler( *args )
  File "/home/varoquau/dev/enthought/ets/envisageplugins/enthought/plugins/python_shell/view/python_shell_view.py", line 242, in _on_write_stdout
    self.shell.control.write(text)
  File "/home/varoquau/dev/enthought/ets/traitsbackendqt/enthought/pyface/ui/qt4/python_shell.py", line 156, in write
    if not self._hidden:
AttributeError: 'PyfacePythonWidget' object has no attribute '_hidden'
ERROR|2011-04-17 23:50:35,962|Exception occurred in traits notification handler for object: <enthought.plugins.python_shell.view.python_shell_view.PythonShellView object at 0xa1e7cbc>, trait: stdout_text, old value: <undefined>, new value: 
Traceback (most recent call last):
  File "/home/varoquau/dev/enthought/ets/traits/enthought/traits/trait_notifiers.py", line 512, in rebind_call_1
    self.dispatch( getattr( self.object(), self.name ), new )
  File "/home/varoquau/dev/enthought/ets/traits/enthought/traits/trait_notifiers.py", line 622, in dispatch
    handler( *args )
  File "/home/varoquau/dev/enthought/ets/envisageplugins/enthought/plugins/python_shell/view/python_shell_view.py", line 242, in _on_write_stdout
    self.shell.control.write(text)
  File "/home/varoquau/dev/enthought/ets/traitsbackendqt/enthought/pyface/ui/qt4/python_shell.py", line 156, in write
    if not self._hidden:
AttributeError: 'PyfacePythonWidget' object has no attribute '_hidden'
Exception occurred in traits notification handler for object: <enthought.pyface.ui.qt4.gui.GUI object at 0xa06823c>, trait: started, old value: False, new value: True
Traceback (most recent call last):
  File "/home/varoquau/dev/enthought/ets/traits/enthought/traits/trait_notifiers.py", line 536, in rebind_call_4
    object, trait_name, old, new )
  File "/home/varoquau/dev/enthought/ets/traits/enthought/traits/trait_notifiers.py", line 448, in dispatch
    handler( *args )
  File "/home/varoquau/dev/enthought/ets/mayavi/enthought/mayavi/plugins/mayavi_ui_plugin.py", line 207, in _on_application_gui_started
    from enthought.naming.ui.api import explore
  File "/home/varoquau/dev/enthought/ets/apptools/enthought/naming/ui/api.py", line 16, in <module>
    from explorer import Explorer, explore
  File "/home/varoquau/dev/enthought/ets/apptools/enthought/naming/ui/explorer.py", line 23, in <module>
    from naming_tree import NamingTree
  File "/home/varoquau/dev/enthought/ets/apptools/enthought/naming/ui/naming_tree.py", line 19, in <module>
    from enthought.pyface.tree.api import NodeTree
ImportError: cannot import name NodeTree
ERROR|2011-04-17 23:50:35,963|Exception occurred in traits notification handler for object: <enthought.pyface.ui.qt4.gui.GUI object at 0xa06823c>, trait: started, old value: False, new value: True
Traceback (most recent call last):
  File "/home/varoquau/dev/enthought/ets/traits/enthought/traits/trait_notifiers.py", line 536, in rebind_call_4
    object, trait_name, old, new )
  File "/home/varoquau/dev/enthought/ets/traits/enthought/traits/trait_notifiers.py", line 448, in dispatch
    handler( *args )
  File "/home/varoquau/dev/enthought/ets/mayavi/enthought/mayavi/plugins/mayavi_ui_plugin.py", line 207, in _on_application_gui_started
    from enthought.naming.ui.api import explore
  File "/home/varoquau/dev/enthought/ets/apptools/enthought/naming/ui/api.py", line 16, in <module>
    from explorer import Explorer, explore
  File "/home/varoquau/dev/enthought/ets/apptools/enthought/naming/ui/explorer.py", line 23, in <module>
    from naming_tree import NamingTree
  File "/home/varoquau/dev/enthought/ets/apptools/enthought/naming/ui/naming_tree.py", line 19, in <module>
    from enthought.pyface.tree.api import NodeTree
ImportError: cannot import name NodeTree
</pre>

Trying to close:

<pre>
Exception occurred in traits notification handler for object: <enthought.mayavi.plugins.envisage_engine.EnvisageEngine object at 0xa0509bc>, trait: children_ui_list, old value: scenes_items, new value: []
Traceback (most recent call last):
  File "/home/varoquau/dev/enthought/ets/traits/enthought/traits/trait_notifiers.py", line 528, in rebind_call_3
    object, trait_name, new )
  File "/home/varoquau/dev/enthought/ets/traits/enthought/traits/trait_notifiers.py", line 622, in dispatch
    handler( *args )
  File "/home/varoquau/dev/enthought/ets/traitsbackendqt/enthought/traits/ui/qt4/tree_editor.py", line 1321, in _children_replaced
    child, child_node = self._node_for( child )
  File "/home/varoquau/dev/enthought/ets/traitsbackendqt/enthought/traits/ui/qt4/tree_editor.py", line 530, in _node_for
    nodes   = [ node for node in factory.nodes
AttributeError: 'NoneType' object has no attribute 'nodes'
ERROR|2011-04-17 23:51:51,054|Exception occurred in traits notification handler for object: <enthought.mayavi.plugins.envisage_engine.EnvisageEngine object at 0xa0509bc>, trait: children_ui_list, old value: scenes_items, new value: []
Traceback (most recent call last):
  File "/home/varoquau/dev/enthought/ets/traits/enthought/traits/trait_notifiers.py", line 528, in rebind_call_3
    object, trait_name, new )
  File "/home/varoquau/dev/enthought/ets/traits/enthought/traits/trait_notifiers.py", line 622, in dispatch
    handler( *args )
  File "/home/varoquau/dev/enthought/ets/traitsbackendqt/enthought/traits/ui/qt4/tree_editor.py", line 1321, in _children_replaced
    child, child_node = self._node_for( child )
  File "/home/varoquau/dev/enthought/ets/traitsbackendqt/enthought/traits/ui/qt4/tree_editor.py", line 530, in _node_for
    nodes   = [ node for node in factory.nodes
AttributeError: 'NoneType' object has no attribute 'nodes'
Traceback (most recent call last):
  File "/home/varoquau/dev/enthought/ets/traitsbackendqt/enthought/pyface/ui/qt4/gui.py", line 188, in event
    self._callable(*self._args, **self._kw)
  File "/home/varoquau/dev/enthought/ets/traitsgui/enthought/pyface/workbench/workbench_window.py", line 181, in close
    self.destroy_editors(self.editors)
  File "/home/varoquau/dev/enthought/ets/traitsgui/enthought/pyface/workbench/workbench_window.py", line 330, in destroy_editors
    editor.destroy_control()
  File "/home/varoquau/dev/enthought/ets/mayavi/enthought/tvtk/plugins/scene/scene_editor.py", line 75, in destroy_control
    return super(SceneEditor, self).destroy_control()
  File "/home/varoquau/dev/enthought/ets/traitsbackendqt/enthought/pyface/ui/qt4/workbench/editor.py", line 52, in destroy_control
    self.control.deleteLater()
AttributeError: 'NoneType' object has no attribute 'deleteLater'
Traceback (most recent call last):
  File "/home/varoquau/dev/enthought/ets/traitsbackendqt/enthought/pyface/ui/qt4/workbench/workbench_window_layout.py", line 572, in sizeHint
    sh = self.centralWidget().sizeHint()
AttributeError: 'NoneType' object has no attribute 'sizeHint'
Traceback (most recent call last):
  File "/home/varoquau/dev/enthought/ets/traitsbackendqt/enthought/pyface/ui/qt4/workbench/workbench_window_layout.py", line 572, in sizeHint
    sh = self.centralWidget().sizeHint()
AttributeError: 'NoneType' object has no attribute 'sizeHint'
Traceback (most recent call last):
  File "/home/varoquau/dev/enthought/ets/traitsbackendqt/enthought/pyface/ui/qt4/workbench/workbench_window_layout.py", line 572, in sizeHint
    sh = self.centralWidget().sizeHint()
AttributeError: 'NoneType' object has no attribute 'sizeHint'
Traceback (most recent call last):
  File "/home/varoquau/dev/enthought/ets/traitsbackendqt/enthought/pyface/ui/qt4/workbench/workbench_window_layout.py", line 572, in sizeHint
    sh = self.centralWidget().sizeHint()
AttributeError: 'NoneType' object has no attribute 'sizeHint'
</pre>

**Comment by epatters** [comment]
At least some of these errors appear related to recent changes I made to the Python shell. I'll look into this.

**Comment by GaelVaroquaux** [comment]
On Sun, Apr 17, 2011 at 08:40:10PM -0700, epatters wrote:

> At least some of these errors appear related to recent changes I made to the Python shell. I'll look into this.

Thanks Evan!

Gael

**Comment by epatters** [comment]
I fixed the Python shell error (in the new pyface package). The NodeTree error is raised because pyface.tree.Tree is only implemented for wx. What is Explorer used for? Do you need it?

I haven't had a chance to look at the shutdown errors yet.

**Comment by mdickinson** [comment]
Closing prior to archiving the repository.
